### ISSUE TITLE
Trigger form.submit and catch error from outside angular

### ISSUE THREAD

**Issue by istian** [kelp404/angular-validator#30]
Hi,

I can call the form.submit method from outside angular but I can't figure out how to return the result of validator. I need to have a way to check if the form is invalid, return something to the non-angularjs function to halt the process. Is there a way to achieve what I'm trying to do?

Thanks

**Comment by anmolsharma25** [comment]
Hi istian,

Can you share your code.
I am struggling to do the functionality. 
I call submit function from a javascript function but the submit(angularjs function) get executed after the javascript function is executed.

I would really appreciated your help.
Thanks
