### ISSUE TITLE
$validator.reset not working

### ISSUE THREAD

**Issue by CarbonFactory** [kelp404/angular-validator#47]
`$validator.reset($scope, 'scope.formData');` is not working.

I'm using the ControllerAs syntax which is denoted by the `scope` in the above line. 

`$validator.validate($scope, 'scope.formData').success(function() {}).error(function() { });` works just fine.

**Comment by kelp404** [comment]
Is your model like this?
```js
$scope.scope.formData = {};
```

**Comment by CarbonFactory** [comment]
@kelp404  Please close the issue.
