### ISSUE TITLE
radio Button

### ISSUE THREAD

**Issue by a-lucas** [kelp404/angular-validator#7]
Is it working with radio button? Looking at your code, I suspect that it won't work.

**Comment by rikkipitt** [comment]
Hi @a-lucas / @kelp404 

Did you ever figure out how to validate __required__ radio inputs?

Cheers! Rikki

**Comment by rikkipitt** [comment]
I've figured this out, I shall post how I did it soon!

**Comment by obender** [comment]
@rikkipitt  any update ?
I want to add this to the library
